name = "SchwingerBosonXXZ"
uuid = "877ee5be-130f-471f-9300-fbd396a46c7c"
authors = ["Hao Zhang <hzhangphys@gmail.com>"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
NLsolve = "4.5.1"
Optim = "1.13.2"
StaticArrays = "1.9.13"
julia = ">=1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
